export enum EstadoCampanaEnum {
    CREADO = 1,
    ASIGNADA = 2,
    GEOREFERENCIADA = 3,
    GEOREFERENCIADA_Y_MODIFICADA = 4,
    GEOREFERENCIADA_Y_CONFIRMADA = 5,
    COTIZADA = 6,
    CONFORMIDAD_ADJUNTADA = 7,
    CONFORMIDAD_VERIFICADA = 8,
    CONFORMIDAD_DENEGADA = 9
}