export enum EstadoCampanaEnum {
    CREADO = 1,
    ASIGNADA = 2,
    GEOREFERENCIADA = 3,
    GEOREFERENCIADAGEOREFERENCIADA_Y_MODIFICADA = 4,
    GEOREFERENCIADA_Y_CONFIRMADA = 5,
    COTIZADA = 6
}